name: 'Check value'
description: 'Check the value of an input.'
author: 'richardrigutins'

branding:
  icon: 'check-square'
  color: 'blue'

inputs:
  input:
    description: 'The input to check.'
    required: true

outputs:
  has-value:
    description: 'A boolean indicating whether the input has a value.'

runs:
  using: node20
  main: dist/index.js
